### PR TITLE
Feature/error handle2

### PR DESCRIPTION
**Pull request by Montana-Pfeifer**
contains sad path addition for 422 error handling in update

UPDATE: IN POSTMAN THE ITEMS TEST TO UPDATE WAS PUTS I CHANGED IT TO PATCH.
CHANGE VERB FROM PUTS TO PATCH IN POSTMAN FOR ITEMS.

### CODE REVIEW

**Comment by devklynch** [comment]
The tests look good, it looks like the items_controller.rb file needs to be updated to resolve that merge though since it might be behind some updates

**Comment by Montana-Pfeifer** [comment]
> The tests look good, it looks like the items_controller.rb file needs to be updated to resolve that merge though since it might be behind some updates

fixed all conflicts

**Review by ossar3 — APPROVED** [review]

**Comment by ossar3** [comment]
looks good i am 2nd i think so i will merge

**Comment by ossar3** [comment]
never mind i think maybe we need one more approval

**Comment by ossar3** [comment]
oh wait actually we are good it seems

**Pull request merged**
